#! /bin/sh
# I was here

pgrep -x sxhd > /dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

bspc monitor eDP-1 -d 1 2 3 4 5 
bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 1 2 3 4 5

bspc config border_width          2
bspc config window_gap            10 

bspc config split_ratio           0.5
bspc config single_monocle	      false
bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focused_border_color  "#60663d"
bspc config normal_border_color   "#1a1a1a"
bspc config active_border_color   "#60663d"
bspc config presel_feedback_color "#1a1a1a"

# Set background picture
feh --bg-fill $HOME/Pictures/nightdottedstars.jpg
# Compositor
picom -b

xsetroot -cursor_name left_ptr

# CapsLock -> Ctrl (hold) / Esc (tap)
xmodmap -e 'remove Lock = Caps_Lock' \
        -e 'keysym Caps_Lock = Control_L' \
        -e 'add Control = Control_L'

xcape -e 'Control_L=Escape'

# PrintScreen -> Super
xmodmap -e 'keysym Print = Super_L'
xmodmap -e 'add Mod4 = Super_L'

# start dunst for notifications
dunst &

# run udiskie
udiskie --notify &
